name: CI/CD Pipeline

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch: # Allow manual trigger

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run format:check

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build application
        run: npm run build

      - name: Run E2E tests
        id: playwright-tests
        run: npm run test:e2e:report
        continue-on-error: false # Fail the job if tests fail

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-json
          path: test-results/
          retention-days: 30

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Playwright Test Results
          path: test-results/*.json
          reporter: java-junit
          fail-on-error: true # Block PR merge on test failure

      - name: Comment PR with test results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const testStatus = '${{ steps.playwright-tests.outcome }}';
            const emoji = testStatus === 'success' ? '✅' : '❌';
            const status = testStatus === 'success' ? 'PASSED' : 'FAILED';

            const comment = `## ${emoji} Test Results: ${status}\n\n` +
              `**Status:** ${testStatus}\n` +
              `**Workflow:** [View Details](${context.payload.repository.html_url}/actions/runs/${context.runId})\n` +
              `**Artifacts:** Test reports are available in the workflow artifacts\n\n` +
              `---\n` +
              `*Automated comment by CI/CD Pipeline*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  # Optional: Add a status check job that summarizes all checks
  status-check:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: always()
    steps:
      - name: Check if all jobs succeeded
        run: |
          if [ "${{ needs.lint.result }}" != "success" ] || [ "${{ needs.test.result }}" != "success" ]; then
            echo "❌ One or more checks failed"
            exit 1
          fi
          echo "✅ All checks passed!"
